version: '3'

services:
  mariadb:
    image: mariadb:10.5
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    ports:
      - '3306:3306'
    volumes:
      - mariadb_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:5
    depends_on:
      - mariadb
    environment:
      PMA_HOST: mariadb
      PMA_USER: homestead
      PMA_PASSWORD: secret
    ports:
      - '9090:80'

  queue:
    build: .
    command: php artisan queue:work
    depends_on:
      - mariadb
      - redis
      - zenko
    env_file:
      - .env
    volumes:
      - .:/var/www/html
      - /var/www/html/bootstrap/cache
      - /var/www/html/node_modules
      - /var/www/html/storage
      - /var/www/html/vendor

  redis:
    image: redis:5-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  web:
    build: .
    depends_on:
      - mariadb
      - redis
      - zenko
    env_file:
      - .env
    ports:
      - '8080:80'
    volumes:
      - .:/var/www/html
      - /var/www/html/bootstrap/cache
      - /var/www/html/node_modules
      - /var/www/html/storage
      - /var/www/html/vendor

  zenko:
    image: zenko/cloudserver
    environment:
      ENDPOINT: zenko
      REMOTE_MANAGEMENT_DISABLE: '1'
      S3DATAPATH: /data
      S3METADATAPATH: /metadata
    ports:
      - '8000:8000'
    volumes:
      - zenko_data:/data
      - zenko_metadata:/metadata

volumes:
  mariadb_data:
  redis_data:
  zenko_data:
  zenko_metadata:
