name: cd

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Check code-style
        uses: addnab/docker-run-action@v3
        with:
          image: syncloudsoftech/pinter
          options: -v ${{ github.workspace }}:/workspace
          run: pint

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: $DOCKER_IMAGE:${{ github.run_number }}
